### ISSUE TITLE
洛谷判题崩了！！！

### ISSUE THREAD

**Issue by Link14349** [luogu-dev/luogu-rules#14]
现在正在进行比赛，结果永远在编译！！！

<img width="1440" alt="屏幕快照 2019-08-08 20 36 12" src="https://user-images.githubusercontent.com/32408362/62703813-99946280-ba1c-11e9-9a7c-79c6e594da49.png">

**Comment by StudyingFather** [comment]
所以这也不是你在这里开 issue 的理由啊。

**Comment by kkksc03** [comment]
眼睛看不见了还可以治疗，脑袋坏了就没啥好办法了。

**Comment by HappyCodeHC** [comment]
眼睛看不见了还可以治疗，脑袋坏了就没啥好办法了。

**Comment by Link14349** [comment]
希望你的母亲教过你说话嘴巴要放干净点

HappyCodeHC ***@***.***> 于2021年11月25日周四 下午4:10写道：
